services:

  apsso:
    image: ghcr.io/andrepenteado/apsso/apsso
    container_name: apsso
    environment:
      - CATALINA_OPTS=-Dserver.port=30000
    ports:
      - 30000:30000

  apsso-db:
    image: postgres:15.2
    container_name: apsso-db
    environment:
      POSTGRES_USER: apsso-dbuser
      POSTGRES_PASSWORD: apsso-dbpasswd
      POSTGRES_DB: apsso-dbname
    volumes:
      - ./postgresql-apsso/:/var/lib/postgresql/data/
    command: -p 50000
    ports:
      - 50000:50000

  aproove:
    image: ghcr.io/andrepenteado/aproove/aproove
    container_name: aproove
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 5s
    ports:
      - 30002:30002

  aproove-db:
    image: postgres:15.2
    container_name: aproove-db
    environment:
      - POSTGRES_DB=aproove-dbname
      - POSTGRES_USER=aproove-dbuser
      - POSTGRES_PASSWORD=aproove-dbpasswd
    command: -p 50002
    ports:
      - 50002:50002
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/
