services:
  db-server:
    image: postgres:14.5
    container_name: dbserver-ap-roove
    environment:
      - POSTGRES_DB=dbname-ap-roove
      - POSTGRES_USER=dbuser-ap-roove
      - POSTGRES_PASSWORD=dbpasswd-ap-roove
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/

  db-server-test:
    image: postgres:14.5
    container_name: dbserver-ap-roove-test
    environment:
      - POSTGRES_DB=dbname-ap-roove-test
      - POSTGRES_USER=dbuser-ap-roove
      - POSTGRES_PASSWORD=dbpasswd-ap-roove
    ports:
      - 54320:5432
    volumes:
      - ./postgresql-test/:/var/lib/postgresql/data/
