services:

  backend:
    image: ghcr.io/andrepenteado/aproove/backend
    container_name: aproove-backend
    hostname: aproove-backend
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 5s
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 30004:8080
    networks:
      - docker-host-network

  frontend:
    image: ghcr.io/andrepenteado/aproove/frontend
    container_name: aproove-frontend
    hostname: aproove-frontend
    ports:
      - 40004:80
    networks:
      - docker-host-network

networks:
  docker-host-network:
    external: true
