services:

  aproove:
    image: ghcr.io/andrepenteado/aproove/aproove
    container_name: aproove
    hostname: aproove
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 5s
    ports:
      - 30002:30002

  aproove-db:
    image: postgres:15.2
    container_name: aproove-db
    hostname: aproove-db
    environment:
      - POSTGRES_DB=aproove-dbname
      - POSTGRES_USER=aproove-dbuser
      - POSTGRES_PASSWORD=aproove-dbpasswd
    command: -p 50002
    ports:
      - 50002:50002
    volumes:
      - aproove-pgdata:/var/lib/postgresql/data/

volumes:
  apsso-pgdata:
  aproove-pgdata:

