services:

  dev.aproove.apcode.com.br:
    image: ghcr.io/andrepenteado/aproove/aproove
    container_name: aproove
    hostname: aproove
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 5s
    ports:
      - 30003:8080
    networks:
      - docker-host-network

networks:
  docker-host-network:
    external: true
