services:

  aproove-db:
    image: postgres:15.2
    container_name: aproove-db
    environment:
      - POSTGRES_DB=aproove-dbname
      - POSTGRES_USER=aproove-dbuser
      - POSTGRES_PASSWORD=aproove-dbpasswd
    ports:
      - 50002:5432
    volumes:
      - aproove-pgdata:/var/lib/postgresql/data/

  aproove-db-test:
    image: postgres:15.2
    container_name: aproove-db-test
    environment:
      - POSTGRES_DB=aproove-dbname
      - POSTGRES_USER=aproove-dbuser
      - POSTGRES_PASSWORD=aproove-dbpasswd
    ports:
      - 54320:5432
    volumes:
      - aproove-test-pgdata:/var/lib/postgresql/data/

volumes:
  aproove-pgdata:
  aproove-test-pgdata:
