services:

  aproove-db:
    image: postgres:16
    container_name: aproove-db
    environment:
      - POSTGRES_DB=aproove-dbname
      - POSTGRES_USER=aproove-dbuser
      - POSTGRES_PASSWORD=aproove-dbpasswd
    ports:
      - 5432:5432
    volumes:
      - aproove-pgdata:/var/lib/postgresql/data/
    networks:
      - docker-host-network

  aproove-db-test:
    image: postgres:16
    container_name: aproove-db-test
    environment:
      - POSTGRES_DB=aproove-dbname
      - POSTGRES_USER=aproove-dbuser
      - POSTGRES_PASSWORD=aproove-dbpasswd
    ports:
      - 5433:5432
    volumes:
      - aproove-test-pgdata:/var/lib/postgresql/data/
    networks:
      - docker-host-network

volumes:
  aproove-pgdata:
  aproove-test-pgdata:

networks:
  docker-host-network:
    external: true
