spring:
  datasource:
    url: jdbc:postgresql://db-server/aproove-dbname

  security:
    oauth2:
      client:
        registration:
          "[com.github.andrepenteado.roove]":
            provider: com.github.andrepenteado.sso.portal
            client-name: AProove
            client-id: LOCAL-roove
            client-secret: b3b1d7f5-2af6-4a8b-8e7a-0e4629742201
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_basic
        provider:
          "[com.github.andrepenteado.sso.portal]":
            issuer-uri: http://localhost:30000

management:
  tracing:
    enabled: false

frontend:
  pagina-inicial: http://localhost:4200/roove/pagina-inicial