app:

  image:
    repository: "ghcr.io/andrepenteado/aproove/frontend"
    tag: ""
    imagePullSecrets: "github-secret"

  port: 80

  envVars:
    URL_BACKEND: https://sistemas.apcode.com.br/roove-backend

ingress:
  host: "sistemas.apcode.com.br"
  context: "/roove"
