name: Compilar, testar e buildar

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Buildar, testar e gerar imagem

    services:
      aproove-db-test:
        image: postgres:15.2
        env:
          POSTGRES_DB: aproove-dbname
          POSTGRES_USER: aproove-dbuser
          POSTGRES_PASSWORD: aproove-dbpasswd
        ports:
          - 54320:5432

    steps:

    - name: Checkout do projeto
      uses: actions/checkout@v3

    - name: Usar Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Instalar pacotes do frontend
      run: npm --prefix ./frontend install

    - name: Buildar frontend
      run: npm --prefix ./frontend run build --omit=dev

    - name: Usar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: 'maven'

    - name: Compilar e testar backend
      run: mvn -B clean package --file backend/pom.xml

    - name: Buscar versão atual
      run: echo "VERSAO=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file backend/pom.xml)" >> $GITHUB_ENV

    - name: Logar no registry do github
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build da imagem docker
      run: docker build -f docker/Dockerfile.pipeline -t ghcr.io/andrepenteado/aproove/aproove:latest -t ghcr.io/andrepenteado/aproove/aproove:${{ env.VERSAO }} .
    
    - name: Push da imagem docker
      run: |
        docker push ghcr.io/andrepenteado/aproove/aproove:latest
        docker push ghcr.io/andrepenteado/aproove/aproove:${{ env.VERSAO }}
